version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env
    networks:
      - web
  pgadmin4:
    container_name: pgadmin4
    links:
      - postgres
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env
    networks:
      - web
  main:
    container_name: main
    build:
      context: ./
    volumes:
      - './:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - ${PORT}:${PORT}
      - 4000:4000
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - web
    depends_on:
      - postgres
    restart: 'on-failure'
networks:
  web:
    driver: bridge
